### ISSUE TITLE
[Question] Can  com.google.cloud.aiplatform.v1.PredictionServiceClient be a Singleton

### ISSUE THREAD

**Issue by yana2301** [googleapis/java-aiplatform#1013]
Hello, I would like to understand if I can create a single instance of the `com.google.cloud.aiplatform.v1.PredictionServiceClient` for the whole lifespan of the application?

In API docs, in the example of usage of PredictionServiceClient it is created within try-with-resources block, which means it will be recreated for each group of requests: https://cloud.google.com/java/docs/reference/google-cloud-aiplatform/latest/com.google.cloud.aiplatform.v1.PredictionServiceClient 

But in code samples it is stated that it can be reused between requests: https://github.com/googleapis/google-cloud-java/blob/edcca3b226ab51f0857e47a624917435bcf9fe06/java-aiplatform/samples/snippets/src/main/java/aiplatform/PredictTextClassificationSingleLabelSample.java#L50 

I wonder if PredictionServiceClient must be closed after each usage or it's ok to create a single instance per application on application start and close it on application shutdown?

**Comment by suztomo** [comment]
Yes, it's ok to create a single instance per application on your application start and close it on application shutdown.

This example https://cloud.google.com/java/docs/reference/google-cloud-aiplatform/latest/com.google.cloud.aiplatform.v1.PredictionServiceClient is short to illustrate the usage concisely. It also explains:

> Note: close() needs to be called on the PredictionServiceClient object to clean up resources such as threads.

You can use a single instance of the class during the entire lifetime of your application. Unless you call the `close()`, the instance consumes the resources even when your application is not doing anything.
