### ISSUE TITLE
README lists 0.2.0 (instead of 0.3.0)

### ISSUE THREAD

**Issue by alecglassford** [googleapis/java-aiplatform#190]
Version 0.3.0 of this library has been released. However, the README still provides installation instructions for version 0.2.0. I believe it should be updated to provide installation instructions for version 0.3.0.

I almost created a simple PR for this, but the README seems to be edited exclusively by the `yoshi-automation` bot, so I expect some additional configuration might need to happen.

#### Environment details

N/A

#### Steps to reproduce

  1. View https://github.com/googleapis/java-aiplatform/blob/master/README.md
  2. Search for `0.2.0"

#### Code example

N/A

#### Stack trace

N/A

#### External references such as API reference guides

N/A

#### Any additional information below

N/A

**Comment by chingor13** [comment]
The README version is updated automatically and pulls the version from the [`aiplatform_install_without_bom` snippet](https://github.com/googleapis/java-aiplatform/blob/3fae117a6c9d73d292b879c05ba849f0846af73d/samples/install-without-bom/pom.xml#L28-L34)

To resolve this one, #188 needs to be approved and merged.
