### ISSUE TITLE
ImportDataVideoActionRecognitionSampleTest needs correct test input

### ISSUE THREAD

**Issue by telpirion** [googleapis/java-aiplatform#365]
The `GCS_SOURCE_URI` for the test points to a non-existent file:

https://github.com/googleapis/java-aiplatform/blob/master/samples/snippets/src/test/java/aiplatform/ImportDataVideoActionRecognitionSampleTest.java#L45

This needs to point to a new batch prediction file for Video Action Recognition.

**Comment by morgandu** [comment]
Closing the issue as the bucket host GCS_SOURCE_URI was deleted, then resumed.
