### ISSUE TITLE
CreateBatchPredictionJobVideoActionRecognitionSampleTest needs correct input file

### ISSUE THREAD

**Issue by telpirion** [googleapis/java-aiplatform#366]
The GCS_SOURCE_URI for the test points to an incorrect file:

https://github.com/googleapis/java-aiplatform/blob/master/samples/snippets/src/test/java/aiplatform/CreateBatchPredictionJobVideoActionRecognitionSampleTest.java#L39

This needs to point to a new batch prediction file for Video Action Recognition.

**Comment by morgandu** [comment]
Close the issue as it was caused by input files (bucket) deleted, now the bucket is restored.
