### ISSUE TITLE
Testing only one feature and disable tests for similar service

### ISSUE THREAD

**Issue by munkhuushmgl** [googleapis/java-aiplatform#420]
Monthly cost for running all these ITs fairly high compared to other repo IT. Testing all batch prediction jobs on every single batch prediction type is very expensive and means that we frequently hit our quotas. We have increased the quota for our testing project but we still hit the limit.

We proposed that we should only test one core `batchPrediction` sample and disable all other similar `batchPrediction` tests.

Likewise for other ITs.

Error message (example):
```
	Error
		Code: 8
		Message: The following quotas are exceeded: AutoMLTextSentimentConcurrentModelTrainingJobs
```

**Comment by suztomo** [comment]
This repository has migrated to googleapis/google-cloud-java. Integration tests run fine.
