### ISSUE TITLE
Bug in Vertex AI docs

### ISSUE THREAD

**Issue by JoshuaFox** [googleapis/java-aiplatform#668]
Vertex AI Java documentation is incorrect.

I used this code, [copied straight from the Javadocs](https://github.com/googleapis/java-aiplatform/blob/master/google-cloud-aiplatform/src/main/java/com/google/cloud/aiplatform/v1/PipelineServiceClient.java), to delete a VertexAI Training Pipeline

```
try (PipelineServiceClient pipelineServiceClient = PipelineServiceClient.create()) {
  TrainingPipelineName name =
      TrainingPipelineName.of("[PROJECT]", "[LOCATION]", "[TRAINING_PIPELINE]");
  pipelineServiceClient.deleteTrainingPipelineAsync(name).get();
}
```

I get this error.

```
Error in deleting //aiplatform.googleapis.com/projects/746859988231/locations/us-central1/trainingPipelines/186468439399187392: 
java.util.concurrent.ExecutionException: 
com.google.api.gax.rpc.UnimplementedException: io.grpc.StatusRuntimeException:
UNIMPLEMENTED: HTTP status code 404
```

As discussed [here](https://stackoverflow.com/questions/69219230), you have to specify an endpoint -- and then it works.

I suggest fixing   the documentation to produce working code.

**Comment by eaball35** [comment]
These are autogenerated samples, intended to be a guide in the right direction. They are a WIP. These generated samples are updated now to include comment that they may require additional configuration to work (see #892). This isn't a Vertex AI bug (although you could add additional comments to the protos that explain this) but rather a feature request for gapic-generator, so I'll move this there.

**Comment by eaball35** [comment]
Closing - issue moved to generator https://github.com/googleapis/gapic-generator-java/issues/991
